import React from "react";
import Head from "next/dist/shared/lib/head";
import Star from "../components/Packages_SFSP/star_rating";
import { useEffect, useState, useRef } from "react";
import axios from "axios";
// import PackageId from "./package";
import ReactPaginate from "react-paginate";
import Sort from "../components/Packages_SFSP/sort";
// import SearchData from "../components/SearchBar/searchbarnew.json";
import GptSearch from "../components/SearchBar/gptSearch";
// import SearchBar from "../components/SearchBar/SearchBar";
import { useRouter } from "next/router";
import { BrowserRouter as Router, Route } from "react-router-dom";
import { get } from "mongoose";



function App() {


  return (
    <div>
      <Head>
        <title>TripzyGo - Packages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          rel="stylesheet"
          id="bootstrap-css"
        />
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      </Head>
      <section
        className="breadcrumb-main pb-20 pt-16"
        style={{ backgroundImage: "url(images/banner_images/packages.webp)" }}
      >
        <div className="breadcrumb-outer">
          <div className="container" id="searchBarContainer">
            <div className="breadcrumb-content text-center">
              <nav aria-label="breadcrumb" className="d-block">
                <ul className="breadcrumb banner-content">
                  <h2 className="text-white">Get Customized Tour Packages</h2>
                  <div className="text-white mb-2">
                    {" "}
                    Exciting Offers Customised for The Best Travel Packages
                  </div>
                  <br />
                </ul>
                <GptSearch/>
                {/* <br /><br /><br /><br /><br />
                <SearchBar placeholder="Search Destination"  data={SearchData} /> */}
              </nav>
            </div>
          </div>
        </div>
        <div className="dot-overlay"></div>
      </section>


    </div>
  );
}

export default App;
