import React from 'react'
import Blog_data from "../../components/Blogs/blog_data"
import Head from "next/dist/shared/lib/head";
import { useEffect, useState } from 'react'
import axios from 'axios';
// import Pagination from '../components/package_SFSP/pagination';
import Newsletter from './newsletter'
import BlogCategory from "../../components/Blogs/blogcategory"
import BlogRecent from "../../components/Blogs/blogrecent"
import Blogpopular from '../../components/Blogs/blogpopular';
import ReactPaginate from 'react-paginate';
import BlogNavbar from '../../components/Blogs/blog_navbar'


function App() {
    const [obj, setObj] = useState({});
    const [sort, setSort] = useState({ sort: "blog_date_search", order: "desc" });
    const [blogCategory, setblogCategory] = useState([]);
    const [page, setPage] = useState(1);
    const getAllBlogs = async () => {
        try {
            const url = `https://backend.tripzygo.in/blogs?page=${page}&sort=${sort.sort},${sort.order
                }&blog_category_filter=Thingsto do`;
            const { data } = await axios.get(url);
            setObj(data);
            // console.log(data);
        } catch (err) {
            // console.log(err);
        }
    };

    useEffect(() => {
        getAllBlogs();
    }, [sort, blogCategory, page]);

    const pageCount = Math.ceil(obj.total / 6);

    const changePage = ({ selected }) => {
        setPage(selected + 1);
    };

    return (
        <>
            <Head>
                <title>TripzyGo - Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <section class="breadcrumb-main pb-20 pt-14" style={{ backgroundImage: "url(/images/banner_images/blog.webp)" }}>
                <div class="section-shape section-shape1 top-inherit bottom-0" ></div>
                <div class="breadcrumb-outer">
                    <div class="container">
                        <div class="breadcrumb-content text-center">
                            <h1 class="mb-3"> Our Blogs</h1>
                            <nav aria-label="breadcrumb" class="d-block">
                                <ul class="breadcrumb">
                                    {/* <li class="breadcrumb-item"><a href="#">Home</a></li> */}
                                    <li class="breadcrumb-item active" aria-current="page">Get amazing travel advice, tips, and information for your next trip</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="dot-overlay"></div>
            </section>
            <BlogNavbar></BlogNavbar>

            {/* FILTERS */}
            {/* <BlogCategory blogCategory={blogCategory}
                categories={obj.blog_category_options ? obj.blog_category_options : []}
                setblogCategory={(categories) => setblogCategory(categories)}
                reset={() => setblogCategory([])}
            /> */}

            <section className="blog">
                <div className="container">
                    <div className="row flex-row-reverse">
                        <div className="col-lg-8 ps-lg-4">
                            <div className="listing-inner">
                                <div className="row">
                                    <div className="col-lg-12">
                                    </div>
                                    {/* BLOG DATA LANDS HERE */}
                                    <Blog_data blogs={obj.blogs ? obj.blogs : []} />
                                </div>

                                {/* PAGINATION GOES HERE */}
                                {/* <Pagination page={page} limit={obj.limit ? obj.limit : 0}
                                    total={obj.total ? obj.total : 0}
                                    setPage={(page) => setPage(page)}
                                /> */}
                                <div className="container mb-1">
                                    <ReactPaginate
                                        previousLabel={"<<"}
                                        nextLabel={">>"}
                                        breakLabel={"..."}
                                        pageCount={pageCount}
                                        marginPagesDisplayed={0}
                                        pageRangeDisplayed={4}
                                        onPageChange={changePage}
                                        containerClassName={"pagination pagination-sm justify-content-center"}
                                        pageClassName={"page-item"}
                                        pageLinkClassName={"page-link"}
                                        previousClassName={"page-item"}
                                        previousLinkClassName={"page-link"}
                                        nextClassName={"page-item"}
                                        nextLinkClassName={"page-link"}
                                        breakClassName={"page-item"}
                                        breakLinkClassName={"page-link"}
                                        activeClassName={"active"}
                                        disabledClassName={"pagination_next-prevDisabled"}
                                    />
                                </div>
                            </div>
                        </div>

                        {/* RECENT POPULAR NEWS LETTER */}
                        <div className="col-lg-4 pe-lg-3">
                            <div className="sidebar-sticky">
                                <div className="popular-post sidebar-item mb-2">
                                    <div className="trend-item box-shadow bg-white mb-4 rounded overflow-hidden">
                                        <ul className="nav nav-tabs nav-pills nav-fill" id="postsTab1" role="tablist">
                                            <li className="nav-item d-inline-block popularSectionHeading" role="presentation">
                                                <button aria-selected="false" className="nav-link active" data-bs-target="#popular" data-bs-toggle="tab" id="popular-tab" role="tab" type="button">Popular</button>
                                            </li>
                                        </ul>
                                        <div className="tab-content" id="postsTabContent1">
                                            <div aria-labelledby="popular-tab" className="tab-pane fade active show" id="popular" role="tabpanel">
                                                <Blogpopular></Blogpopular>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="recent-post sidebar-item mb-1">
                                    <div className="trend-item box-shadow bg-white mb-4 rounded overflow-hidden">
                                        <div className="post-tabs">
                                            <ul className="nav nav-tabs nav-pills nav-fill" id="postsTab1" role="tablist">
                                                <li className="nav-item d-inline-block" role="presentation">
                                                    <button aria-selected="false" className="nav-link active" data-bs-target="#recent" data-bs-toggle="tab" id="recent-tab" role="tab" type="button">Recent</button>
                                                </li>
                                            </ul>
                                            <div className="tab-content" id="postsTabContent1">
                                                <div aria-labelledby="recent-tab" className="tab-pane fade active show" id="recent" role="tabpanel">
                                                    <BlogRecent></BlogRecent>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <Newsletter></Newsletter>
                            </div>
                        </div>
                    </div>
                </div>
                <script src="/js/jquery-3.5.1.min.js"></script>
                <script src="/js/bootstrap.min.js"></script>
                <script src="/js/particles.js"></script>
                <script src="/js/particlerun.js"></script>
                <script src="/js/plugin.js"></script>
                {/* <script src="/js/main.js"></script> */}
                <script src="/js/custom-accordian.js"></script>
                <script src="/js/custom-nav.js"></script>
                <script src="/js/custom-navscroll.js"></script>
            </section>
        </>
    )
}

export default App;
